[tool.black]
line-length = 100

[tool.coverage.run]
branch = true
cover_pylib = false
source = ["."]

[tool.coverage.html]
directory = "coverage_report"

[tool.coverage.xml]
output = "coverage.xml"

[tool.mypy]
strict = false

[tool.pylint."messages control"]
disable = ["fixme", "missing-class-docstring", "missing-function-docstring"]
